- hosts: demo
  gather_facts: no
  become: yes

  pre_tasks:
    - name: Install required Python packages for Ansible
      yum:
        name:
          - python3
          - python3-libselinux
          - python3-dnf
        state: present
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
